/* Automatically generated by /home/andrea/mygitbucket/contiki-tres/apps/pymite/tools/pmGenPmFeatures.py on Wed Oct 15 13:57:53 2014.  DO NOT EDIT. */
#define HAVE_PRINT
#define HAVE_CLASSES
#define HAVE_REPLICATION
#define HAVE_STRING_FORMAT
#define HAVE_DEBUG_INFO
#define HAVE_ASSERT
#define HAVE_DEFAULTARGS
#define HAVE_DEL
#define HAVE_BACKTICK
#define HAVE_FLOAT
#define HAVE_GC
#define HAVE_IMPORTS
