/* Automatically generated by /home/andrea/icsi/t-res/apps/pymite/tools/pmGenPmFeatures.py on Thu Jun  5 16:26:42 2014.  DO NOT EDIT. */
#define HAVE_PRINT
#define HAVE_CLASSES
#define HAVE_REPLICATION
#define HAVE_GENERATORS
#define HAVE_STRING_FORMAT
#define HAVE_CLOSURES
#define HAVE_DEBUG_INFO
#define HAVE_ASSERT
#define HAVE_DEFAULTARGS
#define HAVE_DEL
#define HAVE_BACKTICK
#define HAVE_FLOAT
#define HAVE_GC
#define HAVE_IMPORTS
