#!/bin/bash

function run {
  MYDIR="$(dirname "$(which "$0")")"
  ${MYDIR}/tres-pf-compile $2
  echo "Creating $1"
  ${MYDIR}/bin/coap-client -m put $1?per=10
  echo "Setting $1/pf /tmp/$2c"
  ${MYDIR}/bin/coap-client -m put $1/pf -b 64 -f /tmp/$2c
  echo "Setting $1/is"
  IFS=',' read -a is <<< "$3"
  echo -n "${is[0]}" | ${MYDIR}/bin/coap-client -m put $1/is -f -
  unset "is[0]"
  for element in "${is[@]}"
  do
    echo -n "$element" | ${MYDIR}/bin/coap-client -m post $1/is -f -
  done
  if [ -n "$4" ]
  then
    echo "Setting $1/od to $4"
    IFS=',' read -a od <<< "$4"
    
    echo -n "${od[0]}" | ${MYDIR}/bin/coap-client -m put $1/od -f -
    unset "od[0]"
    for element in "${od[@]}"
    do
      echo -n "$element" | ${MYDIR}/bin/coap-client -m post $1/od -f -
    done    
  fi
  echo "Start T-Res Task"
  ${MYDIR}/bin/coap-client -m post $1?op=on
}

function print_help {
  scriptname="$(basename "$0")"
  echo "Usage: ${scriptname} <tres_uri> <pf_source file>"           \
    "<input_uri>[,<input_uri>, ...] [<output_uri>]"
}

if [ $# -eq 4 ]
then
  run $1 $2 $3 $4
elif [ $# -eq 3 ]
then
  run $1 $2 $3
else
  print_help "$(basename "$0")"
fi


